# Generated by Django 4.2.11 on 2024-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0004_auto_20230726_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
