# Generated by Django 4.2.11 on 2024-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0005_order_weight_prodcut_weight_alter_order_p_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='p_barcode',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prodcut',
            name='p_barcode',
            field=models.FloatField(),
        ),
    ]
