# Generated by Django 4.2.11 on 2024-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0009_remove_order_p_price_order_p_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_list',
            name='p_price',
        ),
        migrations.AddField(
            model_name='order_list',
            name='p_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
