# Generated by Django 4.2.11 on 2024-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0010_remove_order_list_p_price_order_list_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='products',
            field=models.CharField(default='HI', max_length=255),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='total_weight',
            field=models.IntegerField(default=15),
        ),
    ]
