# Generated by Django 4.2.11 on 2024-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0011_alter_order_list_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_weight',
            field=models.FloatField(default=12),
        ),
    ]
